# Common attributes (used by both urVision and urGovernor)

image_publisher: /teleop/object_detection
object_id_publisher: /teleop/object_ids

weed_data_publisher: /vision/weed_data
crop_data_publisher: /vision/crop_data

velocity_publisher: /current_velocity
framerate_publisher: /current_framerate

weed_threshold_publisher: /vision_target/otsu_threshold

# Fetches the top valid weed to be processed (from tracker)
fetch_weed_service: /fetch_weed_service

# Marks a weed as uprooted (by governor)
mark_uprooted_service: /mark_uprooted_service

# Queries the top valid weed (does not mark as being processed)
query_weeds_service: /query_weeds_service

remove_weed_service: /remove_weed_service

reset_tracker_service: /reset_tracker
stop_tracker_service: /stop_tracker

