# For rosPackageTemplate
subscriber_topic: /temperature

# For Image converter
camera_name: /csi_cam_0
image_topic: /image_raw

image_publisher: /image_converter/output_video
weed_data_publisher: /vision_target/weed_data
weed_threshold_publisher: /vision_target/otsu_threshold

show_img_window: false

# Camera/vision parameters
fov_width_cm: 40
fov_height_cm: 20

min_weed_size_cm: 0
max_weed_size_cm: 1000

default_weed_size_threshold_cm: 26

min_accumulator_size: 10
max_accumulator_size: 100

