# Max allowable time disappeared before removing object (seconds)
max_time_disappeared: 5.0
# Min time to identify the same weed to be valid (seconds)
min_time_valid: 3.0

# Distance tolerance for tracking between frames (in cm)
distance_tolerance: 10
