# Max allowable time disappeared before removing object (seconds)
max_time_disappeared: 20.0
# Min time to identify the same weed to be valid (seconds)
min_time_valid: 1.25

# Distance tolerance for tracking between frames (in cm)
distance_tolerance: 8

# Low-pass filter cut-off for velocity updates (Hz)
vel_lpf_cutoff: 2.0
