# For rosPackageTemplate
subscriber_topic: /temperature

# For Image converter
camera_name: /test_image
image_topic: /image_raw

image_publisher: /image_converter/output_video
weed_data_publisher: /vision_target/weed_data

show_img_window: true

test_image: /home/aruby/catkin_ws/src/urVision/test_images/lettuce.JPG
# Frame rate in Hz
frame_rate: 5

# Camera/vision parameters
fov_width_cm: 45
fov_height_cm: 30

min_weed_size_cm: 1
max_weed_size_cm: 1000

default_weed_size_threshold_cm: 2

min_accumulator_size: 10
max_accumulator_size: 100

x_scale_image: 0.15
y_scale_image: 0.15
