# For Image converter
camera_name: /test_image
image_topic: /image_raw

image_publisher: /image_converter/output_video
weed_data_publisher: /vision_target/weed_data
weed_threshold_publisher: /vision_target/otsu_threshold

show_img_window: false

# Camera/vision parameters
fov_width_cm: 60
fov_height_cm: 45

min_weed_size_cm: 1
max_weed_size_cm: 100

default_weed_size_threshold_cm: 8
default_crop_size_threshold_cm: 8

############################
# Image processing configs #
############################
blur_kernel_size: 20

# Color thresholding
low_hue: 30
low_sat: 95
low_value: 81
high_hue: 90

# Morph operations
morph_size: 3
morph_opening_iterations: 1
morph_closing_iterations: 6

# Blob detection
min_circularity: 0.25
min_convexity: 0.30
min_inertia_ratio: 0.10

# Plant filter decision accumulators
min_accumulator_size: 10
max_accumulator_size: 50