# For rosPackageTemplate
subscriber_topic: /temperature

# For Image converter
camera_name: /test_image
image_topic: /image_raw

image_publisher: /image_converter/output_video
weed_data_publisher: /vision_target/weed_data
weed_threshold_publisher: /vision_target/otsu_threshold

show_img_window: true

# Camera/vision parameters
fov_width_cm: 60
fov_height_cm: 45

min_weed_size_cm: 0
max_weed_size_cm: 100

default_weed_size_threshold_cm: 8
default_crop_size_threshold_cm: 8

# Image processing configs
low_hue: 30
low_sat: 95
low_value: 81

high_hue: 90

morph_size: 2
morph_closing_iterations: 5

min_accumulator_size: 10
max_accumulator_size: 50
