# For Image converter
camera_name: /csi_cam_0
# image_rect_color is rectified camera stream
image_topic: /image_color
show_img_window: false
# Camera calibration file
camera_cal_file: opencv_camera_properties.yaml
# Publishing rate for the REAL framerate
frames_log_interval: 30

# Camera frame parameters (ground projection)
fov_camera_distance_cm: 65
fov_width_cm: 110
fov_height_cm: 61


#####################
# Filtering configs #
#####################
# Any detected objects smaller than this will not be considered
min_weed_size_cm: 2.5
# Any detected objects larger than this will not be considered
max_weed_size_cm: 1000

# Objects within this distance tolerance will be marked as the same object
filter_distance_tolerance_cm: 7

# default thresholds uses for filtering
# MAKE SURE THESE ARE THE SAME
default_weed_size_threshold_cm: 11
default_crop_size_threshold_cm: 11

############################
# Image processing configs #
############################
blur_kernel_size: 15

# Color thresholding
# Hue 30-90 should be green ...
low_hue: 45
low_sat: 55
low_value: 55
high_hue: 90

# Morph operations
morph_size: 2
morph_opening_iterations: 1
morph_closing_iterations: 4

# Blob detection
min_circularity: 0.30
min_convexity: 0.20
min_inertia_ratio: 0.15

# Plant filter decision accumulators
min_accumulator_size: 10
max_accumulator_size: 20

