# For Image converter
camera_name: /test_image
image_topic: /image_raw

camera_cal_file: opencv_camera_properties.yaml

show_img_window: true

# Log framerate every n frames
frames_log_interval: 20

# Camera frame parameters (ground projection)
fov_camera_distance_cm: 55
fov_width_cm: 110
fov_height_cm: 61

# Any detected objects smaller than this will not be considered
min_weed_size_cm: 1
# Any detected objects larger than this will not be considered
max_weed_size_cm: 100

# default thresholds uses for filtering
default_weed_size_threshold_cm: 8
default_crop_size_threshold_cm: 8

############################
# Image processing configs #
############################
blur_kernel_size: 20

# Color thresholding
low_hue: 30
low_sat: 95
low_value: 81
high_hue: 90

# Morph operations
morph_size: 3
morph_opening_iterations: 1
morph_closing_iterations: 6

# Blob detection
min_circularity: 0.25
min_convexity: 0.30
min_inertia_ratio: 0.10

# Plant filter decision accumulators
min_accumulator_size: 10
max_accumulator_size: 50
